enum class FenCheckResult {
    OK,
    INVALID_FEN_SIZE,
    INVALID_BOARD_SIZE,
    INVALID_PIECE,
    INVALID_TURN,
    INVALID_CASTLEABILITY,
    INVALID_ENPASSANT,
    INVALID_HALF_MOVES,
    INVALID_FULL_MOVES
}